apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: hayatroid@gmail.com
    privateKeySecretRef:
      name: cluster-issuer-key
    solvers:
      - http01:
          ingress:
            class: traefik
