apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.13.2/manifests/install.yaml
  - base/argocd-ingress.yaml

patches:
  - path: overlays/argocd-cmd-params-cm.yaml
