apiVersion: v1
kind: ConfigMap
metadata:
  name: data
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Real-time Age Calculator</title>
        <script src="https://cdn.jsdelivr.net/npm/dayjs@1.11.7/dayjs.min.js"></script>
        <style>
            body {
                font-family: Helvetica, Arial, sans-serif;
                margin: 0;
                padding: 20px;
                background-color: #f4f4f9;
                text-align: center;
            }

            h1 {
                color: #333;
            }

            #age {
                font-size: 24px;
                color: #007acc;
                margin-top: 20px;
            }
        </style>
    </head>

    <body>
        <h1>Real-time Age Calculator</h1>
        <div id="age">Your age will appear here.</div>

        <script>
            const ageDisplay = document.getElementById('age');
            const dob = dayjs('2004-12-20');

            const updateAge = () => {
                const now = dayjs();
                ageDisplay.textContent = `${now.diff(dob, 'year', true).toFixed(9)} years old`;
            };

            setInterval(updateAge);
        </script>
    </body>

    </html>
