apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      volumes:
        - name: realtime-age-html
          configMap:
            name: realtime-age-html
      containers:
        - name: caddy
          image: caddy:2.9
          volumeMounts:
            - name: realtime-age-html
              mountPath: /usr/share/caddy
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"
