---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: message
  namespace: default
spec:
  encryptedData:
    index.html: AgCmdwdjcMFaPLpVALjhDc8lk1WoKLm4Qnt1VdafvsLiEwTUo+gBMpINYXJN4TQmVR9V770kYFNW72qPErLpfjhGub56ALaKgtKoUrDgq+sh4AZZlcHjoZ3LgmDrE+hhQNSHQvB4iu4nBIewfbDsVoyidsT8nRipBlJyBooc0GHOZyxvRxNdSvWr6dZaFFKglfdW/efdeYyEXLKzx1H7vqBnCkKRB09WlpyzDSFdD8NsmA7GJDGTWnosr0Kzw6cUmn2LeSPUoFPw1GZaqiunlTf40c5NQI4PZgWo9C8LDVZ8dTgkC4xKbego3KFPo9pgoQ/liGWdp9dsW6wb6mL4Lj+ZdvqjSFP8QzBd+rrnjDTe8q54ZuOAa1dgoQEb12GaMLpEgobRk4o9WntmwHBHfxu3yqF9XuO9lJld7vWYDDbv7Y0hjLLo6kVeaW7pyK+rhxTWixBS3gq93TK1xr41FJKmEOZeB3SRE41I4dsnpdTqC632rGLAHYdqaiNhreEAmZ8Vxv1E5z8U9m3XoSlN2rQkFS78EEx1c1BjfJ5kkHuJvDlon0JE8DrPTYtNE19Q7DUpdhnI5t2AfklgbPXQb3W8s96HW1u1y2MnHRw6DtU5BmGw4ErqnJOR4XhcXapo/k4d/0u7WGwWF2LWcV5x5KE/GpoMi4zbBPt6X/+3iLSnwNB0V6Ve5G4E3mE9IxY2v3uYEL/MaD9jOnqrRwuuJxxoy0HNG9s=
  template:
    metadata:
      creationTimestamp: null
      name: message
      namespace: default
