---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: message
spec:
  encryptedData:
    index.html: AgAB9QBvpdy0rJxKyNa/qx6ZzXa5+CQLMo+UjP5+3EHrDM2n2uf/n1hM+hurDN1qzDrL9Pk+hDiRqDxFGdQdSG7q/BVlSlIeuSWAiv7+dwnsJ64lOLqDN0KhU1KhzKYOTpO6zRPI/owz3195SHmbQS6xen10a3kv9NoC9aDylvK33a/4TAGdLzMRb7ZYOi/r/WtI8vRVxKqrLqW/MRaTnhm2EC2568kPS2V/zi/pb2II/Gxyb3eK7VrhGOIW5tIjNpruvLWXIdAqFS7SdS1W33rY7NsLbpGJ3B2Nvj5a11NAmT7xCRqjii6FkrM4evWn9LkS8uZxjf8SYJoPRylK3J2BUkuY1ymABumffK8ZlaC1uEFg7WC83w16kIVaLMqevyO7kvJ+9LX63X8nrDBOIl0yGtgplmfY8Xb0pq2H7AXj1niFGDw82SUvzYRbOudDi+mGlfKHfTIxgV72bAnE5/XR5YYVAhPa9meWwdITllorklcOyNeAmRi36Sh/Q9YQg6wMr5GPCaDgCxWCiARXcqR4TdQ8kTL/VQZwkUff0qC8pGTepvnLOgqK+bh211xUtXv5tdr0jb2LmiUpJ3pm96j9cmNa16oBj9uHaCDcHgRcSFOnPdoyDf88GJJ4obZQY2spBaTgXyGpBEfsWg3Eumg428+hUR6KIzAbIWpj9S4XoJgxR7k+kKRuMlU9RTKndCe+xPdeeAd8f9q7OHw9BF8hSwtqNsk=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: message
